15:12:15.035 [main] INFO  com.prokarma.base.TestBase - Loading all the required files
15:12:15.041 [main] INFO  com.prokarma.utils.PropertiesReader - Loading the property file : src\test\resources\com\prokarma\config\config.properties
15:12:15.050 [main] INFO  com.prokarma.utils.PropertiesReader - Loading the property file : src\test\resources\com\prokarma\config\request\Request.properties
15:12:15.064 [main] INFO  com.prokarma.utils.PropertiesReader - Loading the property file : src\test\resources\com\prokarma\config\errorhandles\ErrorCodes.properties
15:12:15.067 [main] INFO  com.prokarma.utils.PropertiesReader - src\test\resources\com\prokarma\config\errorhandles\ErrorCodes.properties (The system cannot find the file specified)
java.io.FileNotFoundException: src\test\resources\com\prokarma\config\errorhandles\ErrorCodes.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open(Native Method) ~[na:1.8.0_20]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_20]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[na:1.8.0_20]
	at com.prokarma.utils.PropertiesReader.loadPropertyFile(PropertiesReader.java:33) ~[classes/:na]
	at com.prokarma.base.TestBase.setUp(TestBase.java:44) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84) [testng-6.8.8.jar:na]
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564) [testng-6.8.8.jar:na]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213) [testng-6.8.8.jar:na]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138) [testng-6.8.8.jar:na]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291) [testng-6.8.8.jar:na]
	at org.testng.SuiteRunner.run(SuiteRunner.java:254) [testng-6.8.8.jar:na]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.8.jar:na]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.8.jar:na]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224) [testng-6.8.8.jar:na]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149) [testng-6.8.8.jar:na]
	at org.testng.TestNG.run(TestNG.java:1057) [testng-6.8.8.jar:na]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295) [surefire-testng-2.18.jar:2.18]
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84) [surefire-testng-2.18.jar:2.18]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90) [surefire-testng-2.18.jar:2.18]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.jar:2.18]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.jar:2.18]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.jar:2.18]
15:12:15.068 [main] INFO  com.prokarma.utils.FileUtil - Loading the Excel file : src\test\resources\com\prokarma\testdata\API_Details.xlsx
15:12:15.597 [main] INFO  com.prokarma.utils.DbReader -  Trying to create instance for DB
15:12:15.597 [main] INFO  com.prokarma.utils.DbReader -  Trying to connect database
15:12:16.007 [main] INFO  com.prokarma.utils.DbReader - Access denied for user 'root'@'localhost' (using password: NO)
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946) ~[mysql-connector-java-5.0.8.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985) ~[mysql-connector-java-5.0.8.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:885) ~[mysql-connector-java-5.0.8.jar:na]
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3421) ~[mysql-connector-java-5.0.8.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1247) ~[mysql-connector-java-5.0.8.jar:na]
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2775) ~[mysql-connector-java-5.0.8.jar:na]
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555) ~[mysql-connector-java-5.0.8.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285) ~[mysql-connector-java-5.0.8.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_20]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_20]
	at com.prokarma.utils.DbReader.<init>(DbReader.java:46) [classes/:na]
	at com.prokarma.utils.DbReader.getInstance(DbReader.java:105) [classes/:na]
	at com.prokarma.utils.DB2Manager.<init>(DB2Manager.java:33) [classes/:na]
	at com.prokarma.testfactory.APITestFactory.init(APITestFactory.java:71) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84) [testng-6.8.8.jar:na]
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564) [testng-6.8.8.jar:na]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213) [testng-6.8.8.jar:na]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138) [testng-6.8.8.jar:na]
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175) [testng-6.8.8.jar:na]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107) [testng-6.8.8.jar:na]
	at org.testng.TestRunner.privateRun(TestRunner.java:767) [testng-6.8.8.jar:na]
	at org.testng.TestRunner.run(TestRunner.java:617) [testng-6.8.8.jar:na]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348) [testng-6.8.8.jar:na]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343) [testng-6.8.8.jar:na]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305) [testng-6.8.8.jar:na]
	at org.testng.SuiteRunner.run(SuiteRunner.java:254) [testng-6.8.8.jar:na]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.8.jar:na]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.8.jar:na]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224) [testng-6.8.8.jar:na]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149) [testng-6.8.8.jar:na]
	at org.testng.TestNG.run(TestNG.java:1057) [testng-6.8.8.jar:na]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295) [surefire-testng-2.18.jar:2.18]
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84) [surefire-testng-2.18.jar:2.18]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90) [surefire-testng-2.18.jar:2.18]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.jar:2.18]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.jar:2.18]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.jar:2.18]
15:12:16.010 [main] INFO  c.p.testfactory.APITestFactory - Access denied for user 'root'@'localhost' (using password: NO)
15:12:16.010 [main] INFO  c.p.testfactory.APITestFactory - Test Failed : Access denied for user 'root'@'localhost' (using password: NO)
